development:
  adapter: postgresql
  database: jog_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: jog_test
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000